### ISSUE TITLE
Oops: ClassFormatException An unexpected error occured caused by exception ClassFormatException: null

### ISSUE THREAD

**Issue by divija96** [burrsettles/dualist#7]
play.exceptions.UnexpectedException: Unexpected Error
	at play.classloading.ApplicationCompiler$1.findType(ApplicationCompiler.java:195)
	at play.classloading.ApplicationCompiler$1.findType(ApplicationCompiler.java:144)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:103)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:122)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:1237)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromVariantTypeSignature(LookupEnvironment.java:1293)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeArgumentsFromSignature(LookupEnvironment.java:1080)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:1242)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethod(BinaryTypeBinding.java:509)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethods(BinaryTypeBinding.java:590)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:329)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:674)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:653)
	at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:295)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:108)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:122)
	at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.resolve(ParameterizedTypeBinding.java:851)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:100)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveTypeFor(BinaryTypeBinding.java:1027)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.getField(BinaryTypeBinding.java:829)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findField(Scope.java:988)
	at org.eclipse.jdt.internal.compiler.lookup.BlockScope.getBinding(BlockScope.java:472)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedNameReference.resolveType(QualifiedNameReference.java:905)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:316)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:316)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:186)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:90)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:261)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:90)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:261)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:451)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:212)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:410)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1147)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1235)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:540)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:759)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:464)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:278)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:258)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:138)
	at play.classloading.ApplicationClassloader.loadClass(ApplicationClassloader.java:75)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at play.Play.loadPlugins(Play.java:566)
	at play.Play.init(Play.java:268)
	at play.server.Server.main(Server.java:131)
Caused by: org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:372)
	at play.classloading.ApplicationCompiler$1.findType(ApplicationCompiler.java:163)
	... 47 more
23:52:31,182 WARN  ~ You're running Play! in DEV mode
23:52:31,358 INFO  ~ Listening for HTTP on port 8080 (Waiting a first request to start) ...
23:53:07,900 ERROR ~ 

@75ichnloc
Internal Server Error (500) for request GET /

Oops: ClassFormatException
An unexpected error occured caused by exception ClassFormatException: null

play.exceptions.UnexpectedException: Unexpected Error
	at play.classloading.ApplicationCompiler$1.findType(ApplicationCompiler.java:195)
	at play.classloading.ApplicationCompiler$1.findType(ApplicationCompiler.java:144)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:103)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:122)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:1237)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromVariantTypeSignature(LookupEnvironment.java:1293)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeArgumentsFromSignature(LookupEnvironment.java:1080)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:1242)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethod(BinaryTypeBinding.java:509)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethods(BinaryTypeBinding.java:590)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:329)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:674)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:653)
	at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:295)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:108)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:122)
	at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.resolve(ParameterizedTypeBinding.java:851)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:100)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveTypeFor(BinaryTypeBinding.java:1027)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.getField(BinaryTypeBinding.java:829)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findField(Scope.java:988)
	at org.eclipse.jdt.internal.compiler.lookup.BlockScope.getBinding(BlockScope.java:472)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedNameReference.resolveType(QualifiedNameReference.java:905)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:316)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:316)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:186)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:90)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:261)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:90)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:261)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:451)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:212)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:410)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1147)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1235)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:540)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:759)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:464)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:278)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:258)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:292)
	at play.Play.detectChanges(Play.java:517)
	at play.Invoker$Invocation.init(Invoker.java:100)
	at Invocation.HTTP Request(Play!)
Caused by: org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:372)
	at play.classloading.ApplicationCompiler$1.findType(ApplicationCompiler.java:163)
	... 45 more

**Comment by daj** [comment]
This issue is blocking me from using DUALIST too, even when I give execute permission to `play.plugins`, and remove the `com.apple.quarantine` attribute set by my Mac (obviously doing this is very much at my own risk).  

FTR, the `com.apple.quarantine` attribute was set by Mac OSX after downloading play-1.1.zip from the internet.  I was worried that might have been preventing access to the file, but `dualist gui` didn't work even after removing the attribute:

```
$ chmod +x /Users/Dan/Code/play-1.1/modules/docviewer/app/play.plugins

$ ls -las@ /Users/Dan/Code/play-1.1/modules/docviewer/app/play.plugins
8 -rwxr-xr-x@ 1 Dan  staff  20 Oct  5  2011 /Users/Dan/Code/play-1.1/modules/docviewer/app/play.plugins
	com.apple.quarantine	71

$ xattr /Users/Dan/Code/play-1.1
com.apple.quarantine

$ xattr -r -d com.apple.quarantine /Users/Dan/Code/play-1.1

$ xattr /Users/Dan/Code/play-1.1

$ ls -las@ /Users/Dan/Code/play-1.1/modules/docviewer/app/play.plugins
8 -rwxr-xr-x  1 Dan  staff  20 Oct  5  2011 /Users/Dan/Code/play-1.1/modules/docviewer/app/play.plugins

$ ./dualist gui
~ 
~     __               __ __         __   
~ .--|  |.--.--.---.-.|  |__|.-----.|  |_ 
~ |  _  ||  |  |  _  ||  |  ||__ --||   _|
~ |_____||_____|___._||__|__||_____||____|
~ 
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.1, http://www.playframework.org
~
~ Ctrl+C to stop
~ 
objc[57177]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java (0x1029024c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1041ba4e0). One of the two will be used. Which one is undefined.
Listening for transport dt_socket at address: 8000
11:08:38,255 INFO  ~ Starting /Users/Dan/Code/dualist/gui
11:08:38,929 ERROR ~ 

@784cp6nhp
Cannot load file:/Users/Dan/Code/play-1.1/modules/docviewer/app/play.plugins

Oops: ClassFormatException
An unexpected error occured caused by exception ClassFormatException: null

play.exceptions.UnexpectedException: Unexpected Error
	at play.classloading.ApplicationCompiler$1.findType(ApplicationCompiler.java:195)
	at play.classloading.ApplicationCompiler$1.findType(ApplicationCompiler.java:144)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:103)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:122)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:1237)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromVariantTypeSignature(LookupEnvironment.java:1293)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeArgumentsFromSignature(LookupEnvironment.java:1080)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:1242)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethod(BinaryTypeBinding.java:509)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethods(BinaryTypeBinding.java:590)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:329)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:674)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:653)
	at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:295)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:108)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:122)
	at org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.resolve(ParameterizedTypeBinding.java:851)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:100)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveTypeFor(BinaryTypeBinding.java:1027)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.getField(BinaryTypeBinding.java:829)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findField(Scope.java:988)
	at org.eclipse.jdt.internal.compiler.lookup.BlockScope.getBinding(BlockScope.java:472)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedNameReference.resolveType(QualifiedNameReference.java:905)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:316)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:316)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:186)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:90)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:261)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:90)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:261)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:451)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:212)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:410)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1147)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1235)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:540)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:759)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:464)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:278)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:258)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:138)
	at play.classloading.ApplicationClassloader.loadClass(ApplicationClassloader.java:75)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at play.Play.loadPlugins(Play.java:566)
	at play.Play.init(Play.java:268)
	at play.server.Server.main(Server.java:131)
Caused by: org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:372)
	at play.classloading.ApplicationCompiler$1.findType(ApplicationCompiler.java:163)
	... 47 more
11:08:38,999 WARN  ~ You're running Play! in DEV mode
11:08:39,186 INFO  ~ Listening for HTTP on port 8080 (Waiting a first request to start) ...
```

**Comment by pallysss** [comment]
it happens to me too ,
in my case it's caused by java version. 
i realize my Play using Java 7 but my configuration using java 8.

hope it helps.
